### ISSUE TITLE
Sorting of tools

### ISSUE THREAD

**Issue by xogeny** [modelica/fmi-crosscheck-tools#1]
Sorting should be done alphabetically (in a case insensitive way)

**Comment by xogeny** [comment]
After these scripts are pushed to the Jekyll site, the sorting issue should be fixed (should be later today).

**Comment by xogeny** [comment]
These changes are now visible on https://preview.fmi-standard.org/

**Comment by andreas-junghanns** [comment]
Loving it!!!!
