### ISSUE TITLE
Tool descriptions may contain html syntax (like hrefs) and need to be rendered in the tools pop-up.

### ISSUE THREAD

**Issue by xogeny** [modelica/fmi-crosscheck-tools#6]
This was originally submitted by @andreas-junghanns.  My response was:

This can be done.  But let me know why (so far) it hasn't.  Rendering of HTML in this way a security issue.  It allows somebody somebody to put:

```
Tool such and such is so awesome, you really should use it!
<script>stealAllCredentialsInBrowserMemory();</script>
```

This is why this functionality is avoided and why the feature in React is named [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml).

All that being said, we dont (**currently**) have anything sensitive in memory in the browser since we aren't allowing the user to log in *and* we only allow vendors to specify the HTML.  

**Nevertheless**, I still think this is a bad precedent to set.  An alternative would be to allow text to be written in Markdown and the processed safely with [`react-markdown`](https://www.npmjs.com/package/react-markdown) (which makes a point of not allowing users to do inline HTML, if I understand correctly).

**Comment by xogeny** [comment]
@andreas-junghanns's response was:

> Understood and accepted. Can we auto-convert from html to markup for those files that already exist?
Maybe we should even ban html and reject those files containing html?

I'm still not sure what to do here.  The chance to do this "automatically" as part of the conversion has passed (since we wanted to push forward and put the system into service).

At this point, it will really be up to vendors to fix these issues and perhaps at some future point we can add the ability to support markdown (I'll create a separate ticket for that request).

**Comment by xogeny** [comment]
@andreas-junghanns I'm inclined to close this since I'm not sure what we can do in the immediate future (apart from suggesting to vendors that they remove any markup in their descriptions).  Is there something you think we can do here (apart from what I propose in #7)?

**Comment by andreas-junghanns** [comment]
Are we currently allowing and rendering markup? If so, tell everyone and let them fix it as it looks ugly on their page. Then close this.
If we do not allow markup then that would mean there is no way I can place a link in the description. That would be quite some functionality reduction.

**Comment by xogeny** [comment]
Closing since #7 is implemented and deployed already (*i.e.,* vendors can already start adding markdown to their descriptions).  One lingering issue (beyond the scope of this ticket) is how to notify all vendors of that capability...
