### ISSUE TITLE
The "vendor" MoBA is a tool by vendor TLK

### ISSUE THREAD

**Issue by CSchulzeTLK** [modelica/fmi-crosscheck-tools#8]
The MoBA crosscheck path should be integrated into the TLK crosscheck path.
MoBA Lab is a tool by vendor TLK Thermo. So are TISC and FMI Suite. The two latter ones are already in the TLK vendor path.

**Comment by andreas-junghanns** [comment]
Mike - is this a good test to see if vendors have all the information to move tools from one to another repository; and later close down an entire repo?

**Comment by xogeny** [comment]
Well, @CSchulzeTLK and TLK could pretty easily merge the two repositories into the current TLK one and then I could simply remove the MoBA one when they are done.

**Comment by CSchulzeTLK** [comment]
I was able to add new files to "TLK" but I cannot push the changes in "MoBA".

remote: Permission to fmi-crosscheck/MoBA.git denied to CSchulzeTLK.
fatal: unable to access 'https://github.com/fmi-crosscheck/MoBA/': The requested URL returned error: 403

**Comment by xogeny** [comment]
@CSchulzeTLK Yep, I didn't add you as collaborators for the `MoBA` repo.  What is the plan here?  The goal here is to have one repo per *vendor* (not tool).  I would assume that repo would be the `TLK` repo (since TLK is the vendor).  So perhaps you can outline your plan moving forward here?

**Comment by CSchulzeTLK** [comment]
I moved everything to TLK and was able to commit and push it. I locally deleted the content of the MoBA repo completely but was not able to push the changes. So feel free to simply remove the MoBA repo now, I cannot remove it.

@andreas-junghanns: So I am able to move content from one repo to another, but I am only able to remove file from it, if I am collaborator for that repo. I assume that I am not able to remove the repo.

**Comment by xogeny** [comment]
I've generally given all collaborators Admin privileges on their own repos.  So I suspect vendors could remove their repos if they really wanted to.  This is just a special case because I never gave anybody (apart from me) permissions for MoBA.

**Comment by xogeny** [comment]
For now, I've archived the repository (read-only).  Eventually we can remove it.

I'll close this ticket.
