### ISSUE TITLE
Rename ESi repository name to ESI-ITI

### ISSUE THREAD

**Issue by xogeny** [modelica/fmi-crosscheck-tools#9]
Requested by @tbeu.

**Comment by xogeny** [comment]
Repository renamed.

**Comment by xogeny** [comment]
Yes, I see that.  My best guess is that somehow the legacy data is still getting merged in.  I'll investigate.  I also see `ESi` in `tools.json`, so it isn't just the FMUs.

**Comment by xogeny** [comment]
OK, I think I fixed it.  Close this if you agree.

**Comment by xogeny** [comment]
@beutlich I think this is fixed, but I'm leaving this for you to close...

**Comment by beutlich** [comment]
Not sure which commit fixes it, but searching for ESi still finds

build-server/.gitmodules
widgets/public/sample_data/fmus.json
data-types/__tests__/sample_data/fmus.js
data-types/__tests__/sample_data/tools.js

**Comment by xogeny** [comment]
I got rid of `.gitmodules` in 13a341de15d101b2355561a6002972ae64e35267 (it wasn't even used).  Everything else is just test data.  What I'm asking is whether there is any issue with the data used by the site currently?

**Comment by beutlich** [comment]
@bastianbin OK for you to close?
